FROM swr.cn-north-4.myhuaweicloud.com/ddn-k8s/docker.io/library/node:20-alpine

WORKDIR /app

RUN sed -i 's/dl-cdn.alpinelinux.org/mirrors.ustc.edu.cn/g' /etc/apk/repositories

COPY package*.json ./

RUN npm config set registry https://registry.npmmirror.com && \
    npm install

CMD ["npm", "run", "dev", "--", "--host", "0.0.0.0"]
